print("Welcome to the tip calculator!")
total = float(input("What was the total bill? "))
tip = int ( input("How much tip would you like to give? ") )
people = int ( input ("How many people to split the bill? ") )
each_person = float ( (total + ( total*tip/100 ) ) / people )
print(f"Each person should pay : ${each_person:.2f}")